apiVersion: v1
kind: Secret
metadata:
  name: todolist-secret
  namespace: todolist-grupo-05
  labels:
    app: todolist
    component: secret
  annotations:
    description: "Credenciais e tokens sensíveis do TodoList"
type: Opaque
stringData:
  ADMIN_USER: admin
  ADMIN_PASSWORD: troque-esta-senha
  CLEANUP_TOKEN: troque-este-token
  SESSION_KEY: troque-este-valor
